#!/bin/sh
# Write, start and tear down the THROWAWAY container CI's instance job runs against
# (Story 1.17; README.md's "Verifying the start path against a throwaway container").
#
# **It never points `docker compose` at this repository's own docker-compose.yml.** That file
# names the container `ocupilot` and mounts `./iris-data`, so one missing override line reaches
# a live instance. The compose file this writes is a standalone one in a scratch directory, with
# its own project name, its own container name, its own host ports (never 52774 or 1973) and its
# own data directory, and `down` takes `-v` so nothing of it survives.
#
# The `restart`, `healthcheck` and `command` keys are copied from docker-compose.yml on purpose,
# so a failing start behaves on the throwaway as it would there. Copy them again when they
# change; `ui/tools/compose.test.mjs` pins what they are.
#
# Usage:
#   sh scripts/ci-throwaway.sh up    [--dir DIR] [--project NAME] [--web 52776] [--super 1975]
#   sh scripts/ci-throwaway.sh down  [--dir DIR] [--project NAME]
set -e

ACTION="${1:-}"
shift 2>/dev/null || true

DIR="${OCUPILOT_THROWAWAY_DIR:-/tmp/ocupilot-ci}"
PROJECT="ocupilot-ci"
WEB_PORT="52776"
SUPER_PORT="1975"
IMAGE="intersystems/irishealth-community:2026.2"
REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)

while [ $# -gt 0 ]; do
    case "$1" in
        --dir) DIR="$2"; shift 2 ;;
        --project) PROJECT="$2"; shift 2 ;;
        --web) WEB_PORT="$2"; shift 2 ;;
        --super) SUPER_PORT="$2"; shift 2 ;;
        --image) IMAGE="$2"; shift 2 ;;
        *) echo "ci-throwaway: unknown argument $1"; exit 2 ;;
    esac
done

# The live instance's own ports, refused outright. This script writes a compose file and starts
# a container from it; publishing the live ports would either collide with a running instance or,
# worse, be mistaken for one.
if [ "$WEB_PORT" = "52774" ] || [ "$SUPER_PORT" = "1973" ]; then
    echo "ci-throwaway: 52774 and 1973 are the live container's published ports; a throwaway never takes them"
    exit 2
fi
if [ "$PROJECT" = "ocupilot" ]; then
    echo "ci-throwaway: 'ocupilot' is the live container's own project name; a throwaway never takes it"
    exit 2
fi

COMPOSE_FILE="$DIR/compose.yml"

case "$ACTION" in
    up)
        mkdir -p "$DIR/data" "$DIR/src" "$DIR/scripts" "$DIR/ui"
        # Scratch copies, so a mutation made for a check never touches this repository's files.
        cp -R "$REPO_ROOT/src/." "$DIR/src/"
        cp -R "$REPO_ROOT/scripts/." "$DIR/scripts/"
        # The committed manifest, mounted so that OcuPilot.Test.Manifest's XML parse (DW-197)
        # actually RUNS rather than taking its "no manifest on this instance" skip. That class
        # reads /opt/ocupilot/module.xml, and neither this repository's own compose file nor an
        # earlier version of this script mounted it -- so the one assertion that reads the
        # manifest as a document skipped everywhere, including here, which is the vacuous pass
        # this story exists to remove. Copied rather than bind-mounted from the repository for
        # the reason the two above are.
        cp "$REPO_ROOT/module.xml" "$DIR/module.xml"
        if [ -d "$REPO_ROOT/ui/dist" ]; then
            mkdir -p "$DIR/ui/dist"
            cp -R "$REPO_ROOT/ui/dist/." "$DIR/ui/dist/"
        fi
        cat > "$COMPOSE_FILE" <<EOF
# GENERATED BY scripts/ci-throwaway.sh -- THROWAWAY ONLY, never this repository's docker-compose.yml
name: $PROJECT
services:
  iris:
    image: $IMAGE
    container_name: $PROJECT
    restart: on-failure:3
    ports:
      - "$SUPER_PORT:1972"
      - "$WEB_PORT:52773"
    environment:
      ISC_DATA_DIRECTORY: /durable/iris
      OCUPILOT_DEMO: "1"
    volumes:
      - $DIR/data:/durable
      - $DIR/src:/opt/ocupilot/src:ro
      - $DIR/scripts:/opt/ocupilot/scripts:ro
      - $DIR/ui:/opt/ocupilot/ui:ro
      - $DIR/module.xml:/opt/ocupilot/module.xml:ro
    command: ["--after", "sh /opt/ocupilot/scripts/container-start.sh"]
    healthcheck:
      test: ["CMD", "sh", "/opt/ocupilot/scripts/container-health.sh"]
      interval: 10s
      timeout: 15s
      retries: 30
      start_period: 60s
EOF
        echo "ci-throwaway: wrote $COMPOSE_FILE ($IMAGE, web $WEB_PORT, superserver $SUPER_PORT)"
        docker compose -f "$COMPOSE_FILE" up -d --wait
        docker compose -f "$COMPOSE_FILE" ps
        ;;
    down)
        if [ -f "$COMPOSE_FILE" ]; then
            docker compose -f "$COMPOSE_FILE" logs --no-color iris | tail -n 80 || true
            docker compose -f "$COMPOSE_FILE" down -v
        fi
        rm -rf "$DIR"
        echo "ci-throwaway: removed $DIR"
        ;;
    *)
        echo "ci-throwaway: usage: ci-throwaway.sh up|down [options]"
        exit 2
        ;;
esac
